config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pages#home'

  resources :events do
    resources :participations, only: [:create] do
      # member do
      #   patch :approve
      #   patch :decline
      #   patch :reject
      # end
    end
  end

  resources :participations, only: [:create] do
    member do
      patch 'approve'
      patch 'reject'
    end
    collection do
      get 'pending', as: 'pending'
    end
  end


resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  belongs_to :type

  has_many :participations
  has_many :participants, through: :participations, source: :user
end

app/models/participation.rb
class Participation < ApplicationRecord
  belongs_to :user
  belongs_to :event

  validates :status, presence: true
end

app/models/type.rb
class Type < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :participations
  has_many :participated_events, through: :participations, source: :event
end

app/models/user_event.rb
class UserEvent < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :surname, :city, :date_of_birth, :phone_number])
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[show edit update destroy]
  skip_before_action :authenticate_user!, only: [:index, :show]

# SEARCH QURY CODE IMPORTANT
def index
  @events = Event.where(visibility: true).page(params[:page]).per(6)


  # Filtering by search query
  if params[:query].present?
    sql_subquery = <<~SQL
      events.title ILIKE :query
      OR events.description ILIKE :query
      OR types.name ILIKE :query
    SQL
    @events = @events.joins(:type).where(sql_subquery, query: "%#{params[:query]}%")
  end

  # Filtering by city
  if params[:city].present? && params[:city] != "All"
    @events = @events.where(city: params[:city])
  end
end


  def show
    if current_user == @event.user
      @approved_participants = @event.participations.where(status: 'approved')
      @pending_participations = @event.participations.where(status: 'pending')
    end
  end

  def new
    @event = Event.new
    @types = Type.all
  end

  def edit
    # @event is already set by the before_action
  end

  def create
    @event = Event.new(event_params)
    @event.user = current_user
    if @event.save
      redirect_to @event, notice: 'Event was successfully created.'
    else
      render :new, alert: @event.errors.full_messages
    end
  end

  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
    end
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :description, :city, :capacity, :date, :address, :type_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/participations_controller.rb
# app/controllers/participations_controller.rb
class ParticipationsController < ApplicationController
  # Ensure the user is authenticated for all actions except 'pending'
  before_action :authenticate_user!
  before_action :set_participation, only: [:approve, :decline, :reject]

  def approve
    if @participation.update(status: 'approved')
      redirect_to event_path(@participation.event), notice: 'Participation approved.'
    else
      redirect_to event_path(@participation.event), alert: 'Failed to approve participation.'
    end
  end

  def decline
    if @participation.update(status: 'declined')
      redirect_to event_path(@participation.event), notice: 'Participation request declined.'
    else
      redirect_to event_path(@participation.event), alert: 'Failed to decline participation.'
    end
  end

  def create
    @event = Event.find(params[:event_id])
    @participation = @event.participations.create(user: current_user, status: 'pending')

    if @participation.save
      redirect_to pending_participations_path, notice: 'You have successfully requested to participate in the event.'
    else
      redirect_to @event, alert: 'Failed to request participation.'
    end
  end

  def pending
    @pending_participations = current_user.participations
  end

  def reject
    if @participation.update(status: 'rejected')
      redirect_to @participation.event, notice: 'Participation rejected.'
    else
      redirect_to @participation.event, alert: 'Failed to reject participation.'
    end
  end

  private

  def set_participation
    @participation = Participation.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def age(dob)
    return nil if dob.nil?  # Handle the case where dob is nil

    now = Time.now.utc.to_date
    dob = dob.to_date if dob.respond_to?(:to_date)  # Convert to date if it's not already a date

    now.year - dob.year - (dob.change(year: now.year) > now ? 1 : 0)
  end
end

app/views/events/_event.html.erb
<div class="container"><div id="<%= dom_id event %>">
  <p>
    <strong>Name:</strong>
    <%= event.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= event.description %>
  </p>

    <p>
    <strong>Address:</strong>
    <%= event.address %>
  </p>

  <p>
    <strong>Capacity:</strong>
    <%= event.capacity %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= event.date %>
  </p>

  <div style="width: 100%; height: 600px;"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>


</div>
</div>

app/views/events/_form.html.erb
<div class="form-container">
  <%= simple_form_for(@event) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">
      <div class="form-column">
        <%= f.input :title, label: 'Event Title' %>
        <%= f.input :description, label: 'Event Description' %>
        <%= f.input :city, label: 'City' %>
        <%= f.input :address, label: 'Address' %>
      </div>
      <div class="form-column">
        <%= f.input :capacity, label: 'Capacity' %>
        <%= f.input :date, label: 'Event Date' %>
        <%= f.input :price, label: 'Price' %>
        <%= f.input :type_id, as: :select, collection: @types, label: 'Event Type' %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.button :submit, class: 'btn-submit' %>
    </div>
  <% end %>
</div>

app/views/events/_info_window.html.erb
<h2><%= event.name %></h2>
<p><%= event.address %></p>

app/views/events/edit.html.erb
<div class="container"><h1>Edit your event</h1>

<%= render "form", event: @event %>

<br>

<div>
  <%= link_to "Show this event", @event %> |
  <%= link_to "Back to events", events_path %>
</div>
</div>

app/views/events/index.html.erb
<div id="indexpage">
  <div class="banner-imageIndex"></div>

  <div class="city-dropdown">
    <%= form_with url: events_path, method: :get, local: true do |form| %>
      <%= form.label :city, "Select the city you interested in" %>
      <%= form.select :city, options_for_select(["All", "Agadir", "Casablanca", "Marrakech", "Rabat", "Tangier"], params[:city]), {}, { onchange: "this.form.submit();" } %>
    <% end %>
  </div>

  <div class="container">
    <div class="row">
      <% if @events.any? %>
        <% @events.each do |event| %>
          <div class="col-md-4 mb-4">
            <div class="card h-100">
              <!-- Hardcoded Image -->
              <% if event.type_id == 1 %>
                <img src="https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Y29uY2VydHxlbnwwfHwwfHx8Mg%3D%3D" alt="<%= event.title %>" class="card-img-top">
              <% elsif event.type_id == 3 %>
                <img src="https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OXx8eW9nYXxlbnwwfHwwfHx8Mg%3D%3D" alt="<%= event.title %>" class="card-img-top">
              <% elsif event.type_id == 6 %>
                <img src="https://images.unsplash.com/photo-1550096141-7263640aa48c?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjV8fGNvbW11bml0eXxlbnwwfHwwfHx8Mg%3D%3D" alt="<%= event.title %>" class="card-img-top">
              <% elsif event.type_id == 5 %>
                <img src="https://images.unsplash.com/photo-1544928147-79a2dbc1f389?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mzd8fHdvcmtzaG9wfGVufDB8fDB8fHwy" alt="<%= event.title %>" class="card-img-top">
              <% elsif event.type_id == 4 %>
                <img src="https://images.unsplash.com/photo-1639763703351-c27defbb51b1?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8dG91ciUyMGd1aWRlfGVufDB8fDB8fHwy" alt="<%= event.title %>" class="card-img-top">
              <% elsif event.type_id == 2 %>
                <img src="https://images.unsplash.com/photo-1683117855296-979f17e62e87?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" alt="<%= event.title %>" class="card-img-top">
              <% else %>
                <img src="https://images.unsplash.com/photo-1621112904887-419379ce6824?q=80&w=2072&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" alt="<%= event.title %>" class="card-img-top">
              <% end %>

              <div class="card-body">
                <h5 class="card-title"><%= event.title %></h5>
                <h6 class="card-subtitle mb-2 text-muted"><%= event.date.strftime('%B %d') %></h6>

                <p class="card-text">
                  <i class="fas fa-info-circle"></i>
                  <strong>Description:</strong> <%= truncate(event.description, length: 100) %><br>
                  <i class="fas fa-map-marker-alt"></i>
                  <strong>Location:</strong> <%= event.address %><br>
                  <i class="fas fa-envelope"></i>
                  <strong>Organizer:</strong> <a href="mailto:<%= event.user.email %>"><%= event.user.email %></a>
                </p>
              </div>

              <div class="card-footer">
                <span class="price"><%= event.price %> MAD</span>
                <a href="<%= event_path(event) %>" class="btn btn-primary btn-sm">Book Now</a>
              </div>
            </div>
          </div>
        <% end %>
      <% else %>
        <div class="no-events-message">
          <%= "Sorry, there are no events available in #{params[:city]} at the moment." if params[:city].present? && params[:city] != "All" %>
          <%= "Sorry, there are no events available at the moment." if params[:city].blank? || params[:city] == "All" %>
        </div>
      <% end %>
    </div>

    <%= paginate @events %>
  </div>
</div>

app/views/events/new.html.erb
<div id="mainformCreate">
<div class="container"><center><h1>Create your event</h1></center>

<%= render "form", event: @event %>

<br>

<div class="back-link-container">
  <%= link_to events_path, class: 'back-link' do %>
  <span>
  <i class="fas fa-arrow-left"></i> Back to events
  </span>

  <% end %>
</div>
</div>

app/views/events/show.html.erb
<div id="mainID" data-controller="popup">
  <% if current_user == @event.user %>
  <div class="event-participants">
    <h3 class="list-heading">Pending Participants</h3>
    <ul class="participant-list">
      <% @event.participations.where(status: 'pending').each do |participation| %>
        <li id="participation-<%= participation.id %>" class="participant-item">
          <span><%= participation.user.name %> <%= participation.user.surname %></span>

          <!-- Approve Form -->
          <%= form_with url: approve_participation_path(participation), method: :patch, local: true, class: 'inline-form' do %>
            <button type="submit" class="accept-button"><i class="fa fa-check"></i></button>
          <% end %>

          <!-- Reject Form -->
          <%= form_with url: reject_participation_path(participation), method: :patch, local: true, class: 'inline-form' do %>
            <button type="submit" class="decline-button"><i class="fa fa-times"></i></button>
          <% end %>

        </li>
      <% end %>
    </ul>
  </div>
<% end %>
  <div class="container">
    <div class="event-header">
          <% if @event.type_id == 1 %>
            <img src="https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Y29uY2VydHxlbnwwfHwwfHx8Mg%3D%3D" class="event-image">
          <% elsif @event.type_id == 3 %>
            <img src="https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OXx8eW9nYXxlbnwwfHwwfHx8Mg%3D%3D" class="event-image">
          <% elsif @event.type_id == 6 %>
            <img src="https://images.unsplash.com/photo-1550096141-7263640aa48c?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjV8fGNvbW11bml0eXxlbnwwfHwwfHx8Mg%3D%3D" class="event-image">
          <% elsif @event.type_id == 5 %>
            <img src="https://images.unsplash.com/photo-1544928147-79a2dbc1f389?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mzd8fHdvcmtzaG9wfGVufDB8fDB8fHwy" class="event-image">
          <% elsif @event.type_id == 4 %>
            <img src="https://images.unsplash.com/photo-1639763703351-c27defbb51b1?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8dG91ciUyMGd1aWRlfGVufDB8fDB8fHwy" class="event-image">
          <% elsif @event.type_id == 2 %>
            <img src="https://images.unsplash.com/photo-1683117855296-979f17e62e87?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"  class="event-image">
          <% else %>
            <img src="https://images.unsplash.com/photo-1621112904887-419379ce6824?q=80&w=2072&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" class="event-image">
          <% end %>

      <div class="event-details">
        <h1 class="event-title"><%= @event.title %></h1>
        <p class="event-organizer">
          <span class="by">by</span> <span id="user-name"><%= @event.user.email.split('@').first %></span>
        </p>
        <p class="event-date">
          <i class="fas fa-calendar-alt"></i> <%= @event.date.strftime('%d %B %Y - %H:%M') %>
        </p>
        <p class="event-location">
          <i class="fas fa-map-marker-alt"></i> <%= @event.address %>
        </p>
        <p class="event-attendance">
          <i class="fas fa-users"></i> <%= @event.capacity %> people can attend
        </p>
        <div class="event-actions">
          <button class="btn price-btn event-details-btn">
            <i class="fas fa-tag"></i> <%= number_to_currency(@event.price, unit: 'MAD') %>
          </button>
          <!-- Button to Trigger Pop-Up -->
          <button id="participate-button" class="btn save-btn event-details-btn" data-event-id="<%= @event.id %>">
            <i class="fas fa-bookmark"></i> Participate
          </button>
          <button class="btn share-btn event-details-btn">
            <i class="fas fa-share-alt"></i> Share
          </button>
        </div>
      </div>

    </div>

    <div class="event-description">
      <h3><i class="fas fa-info-circle"></i> Description :</h3>
      <p><%= @event.description %></p>
    </div>

    <div class="event-organizer-info">
      <h3><i class="fas fa-user-tie"></i> Organised by:</h3>
      <p><%= @event.user.email.split('@').first %></p>
    </div>

    <div class="event-tags">
      <h3><i class="fas fa-tags"></i> Tags:</h3>
      <span class="tag"><%= @event.type.name %></span>
    </div>

    <div class="event-map">
      <h3><i class="fas fa-map"></i> Location</h3>
      <iframe src="https://maps.google.com/maps?q=<%= @event.address %>&t=&z=13&ie=UTF8&iwloc=&output=embed" width="100%" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>
    </div>

    <div class="event-actions-footer">
      <%= link_to "<i class='fas fa-edit'></i> Edit this event".html_safe, edit_event_path(@event), class: 'action-link edit-link' %> |
      <%= link_to "<i class='fas fa-arrow-left'></i> Back to events".html_safe, events_path, class: 'action-link back-link' %>
      <%= button_to "<i class='fas fa-trash'></i> Destroy this event".html_safe, @event, method: :delete, class: 'action-link delete-link' %>
    </div>
  </div>

<!-- Pop-Up Modal -->
<div id="participation-modal" class="modal">
  <div class="modal-content">
    <span class="close">&times;</span>
    <h2>Are you sure you want to participate in this event?</h2>
    <%= form_with url: participations_path(event_id: @event.id), method: :post, local: true, id: 'participate-form' do %>
      <%= hidden_field_tag :event_id, @event.id %>
      <button type="submit" class="btn btn-success">Yes, I'm sure</button>
      <button type="button" class="btn btn-danger" id="cancel-participation">No, Cancel</button>
    <% end %>
  </div>
</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vivacity</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render "shared/flashes" %>
    <%= render "shared/navbar" %>
    <%= yield %>
    <%= render "shared/footer" %>

  </body>
</html>

app/views/participations/pending.html.erb
<div class="pending-container">
  <div class="pending-header">
    <h1>Your Participation Requests</h1>
  </div>

  <div class="pending-content">
    <% if @pending_participations.present? %>
      <ul class="pending-list">
        <% @pending_participations.each do |participation| %>
          <li class="pending-item">
            <div class="pending-event">
              <h2><%= participation.event.title %></h2>
              <p><strong>Status:</strong> <span class="status-badge status-<%= participation.status.downcase %>"><i></i> <%= participation.status %></span></p>
              <p><strong>Date:</strong> <%= participation.event.date.strftime('%d %B %Y - %H:%M') %></p>
              <p><strong>Location:</strong> <%= participation.event.address %></p>
              <p><strong>Capacity:</strong> <%= participation.event.capacity %> people</p>
            </div>
          </li>
        <% end %>
      </ul>
    <% else %>
      <p>You have no pending participation requests.</p>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-content">
    <!-- For Personal Section -->
    <div class="footer-section">
      <img src="https://res.cloudinary.com/dneopsx5s/image/upload/v1721648083/VIVA_CITY_v0tse4.png" alt="Vivacity Logo">
      <ul>
        <li>123 Example Street, Casablanca</li>
        <li>(+212) 660-000000</li>
        <li><a href="mailto:Vivacity@gmail.com">Vivacity@gmail.com</a></li>
        <li><a href="http://www.vivacity.ma">www.vivacity.ma</a></li>
      </ul>
    </div>
    <!-- Company Section -->
    <div class="footer-section">
      <h5>Company</h5>
      <ul>
        <li><a href="#">About Us</a></li>
        <li><a href="#">How it works</a></li>
      </ul>
    </div>
    <!-- Connect with Us Section -->
    <div class="footer-section">
      <h5>Connect with us</h5>
      <ul>
        <li><a href="#">Contact Us</a></li>
      </ul>
    </div>
    <!-- Email Subscription Section -->
    <div class="footer-section">
      <h5>Subscribe</h5>
      <form action="#" method="post">
        <input type="email" placeholder="Your email address" required>
        <button type="submit" class="btn btn-footer">Subscribe</button>
      </form>
      <div class="social-icons mt-2">
        <a href="#"><i class="fab fa-linkedin-in"></i></a>
        <a href="#"><i class="fab fa-facebook-f"></i></a>
        <a href="#"><i class="fab fa-twitter"></i></a>
        <a href="#"><i class="fab fa-instagram"></i></a>
      </div>
    </div>
  </div>
  <div class="footer-bottom">
    <div>
      <p class="mb-0">Copyright © 2024, Vivacity Technology Limited</p>
    </div>
    <div>
      <a href="#" class="me-2">Privacy Policy</a>
      <a href="#">Cookie Policy</a>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= root_path %>">
      <img src="https://res.cloudinary.com/dneopsx5s/image/upload/v1721648083/VIVA_CITY_v0tse4.png" alt="Brand Logo" class="avatar-square"/>
    </a>

    <div class="collapse navbar-collapse" id="navbarSupportedContent1">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <a class="nav-link" href="<%= events_path %>">Browse Events</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= new_event_path %>">Add your Event</a>
        </li>
      </ul>
    </div>

    <div class="search-input">
      <%= form_with url: events_path, method: :get, class: "d-flex" do %>
        <%= text_field_tag :query, params[:query], class: "form-control", placeholder: "Type something" %>
        <button type="submit" class="btn btn-primary"><i class="fa fa-search"></i></button>
      <% end %>
    </div>

    <div class="collapse navbar-collapse" id="navbarSupportedContent2">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= pending_participations_path %>">Your Events</a>
          </li>
          <li class="nav-item dropdown">
            <% case current_user.email
               when 'john.doe@example.com'
                 avatar_url = "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Y29uY2VydHxlbnwwfHwwfHx8Mg%3D%3D"
               when 'jane.smith@example.com'
                 avatar_url = "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OXx8eW9nYXxlbnwwfHwwfHx8Mg%3D%3D"
               when 'sara.bouiala@gmail.com'
                 avatar_url = "https://res.cloudinary.com/dneopsx5s/image/upload/v1724696216/Sara_Bouiala_pc2fnl.png"
               when 'othmanebenchekroun@gmail.com'
                 avatar_url = "https://res.cloudinary.com/dneopsx5s/image/upload/v1724696256/PHOTO_PRO_e0wcqa.png"
               else
                 avatar_url = "https://images.unsplash.com/photo-1621112904887-419379ce6824?q=80&w=2072&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
               end %>

            <img src="<%= avatar_url %>" class="avatar-square avatar-round dropdown-toggle" alt="User Avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-expanded="false">
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Profile", user_path(current_user), class: "dropdown-item" %> <!-- Added Profile Link -->
              <%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete }, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item dropdown">
            <img class="avatar-square avatar-round dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://img.icons8.com/?size=100&id=85050&format=png&color=025956" alt="Default Avatar">
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Login", new_user_session_path, class: "dropdown-item" %>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>